image: docker:stable

services:
  - docker:18.06-dind

variables:
  IMAGE_APP: registry.gitlab.com/s.ventura/prosvil1/web:latest
  IMAGE_DB: registry.gitlab.com/s.ventura/prosvil1/db:latest
  
before_script:
- apk add --update python py-pip python-dev 
- pip install docker-compose 
- pip install --upgrade pip
- docker-compose build
- docker-compose up -d
#- docker login registry.gitlab.com --username s.ventura6@campus.unimib.it --password simbacane\12

# stage per indicare che i tre passaggi devono essere eseguiti in sequenza e tutti devono avere successo
stages:
- build
- test
- deploy

build:
 stage: build
 script:
   - echo "Build successfull"

test:
 stage: test
 script:
 - echo "Start testing"
 - docker ps
 - docker-compose exec -T prosvil1_web pytest -q /code/tests/test_templates.py 
 - echo "End testing"

deploy:
 stage: deploy
 script:
 - echo "Starting upload new image "
 - echo "End uploading"