image: python:2.7


before_script:
    - pip install -r requirements.txt
    
stages:
  - build
  - test
  - deploy
  
build:
  - echo "sono nella fase di build"
  script:
     - docker-compose up    
     only :
       changes:
          - Dockerfile
          - app/Dockerfile
          - docker-compose
          - requirements

test:
  script:
     - echo "sono nella fase di test"
    #- python -m pytest tests/test.py
     - python tests/test.py
     
deploy:
   script:
      - echo "sono nella fase di deploy"
     
     
