image: docker:stable

services:
  - docker:dind
  
before_script:
- apk add --update python py-pip python-dev && pip install docker-compose && pip install --upgrade pip
- docker version
- docker-compose version

#variables:
 #MYSQL_DATABASE: AppDB
 #MYSQL_ROOT_PASSWORD: root
    
stages:
- build
- test

build:
 script:
 - echo "sono nella fase di build"
 - cd db
 - docker build -t db .
 - cd ../app
 - docker build -t app .
 #- docker image ls
 #- docker ps
 - docker run --name db_service -e MYSQL_ROOT_PASSWORD=root -d db
 - docker ps
 - docker run --name app_service --link db_service -d app python app.py
 only :
  changes:
  - Dockerfile
  - app/Dockerfile
  - docker-compose
  - app/requirements.txt
  
  


     
     
