image: docker:stable

before_script:
- pip install -r requirements.txt

services:
  - docker:din
    
stages:
- build
- test
- deploy

build:
 script:
 - echo "sono nella fase di build"
 - docker info
 #- docker-compose up    
 #only :
  #changes:
  #- Dockerfile
  #- app/Dockerfile
  #- docker-compose
  #- requirements

test:
 script:
 - echo "sono nella fase di test"
 #- python -m pytest tests/test.py
 - python tests/test.py
     
deploy:
 script:
 - echo "sono nella fase di deploy"

     
     
