image: docker:stable

services:
  - docker:dind
  
before_script:
- apk add --update python py-pip python-dev && pip install docker-compose && pip install --upgrade pip
- docker version
- docker-compose version

stages:
- build
- test

# test if build is correctly after change file of docker setting
build:
 script:
 - echo "sono nella fase di build"
 - cd db
 - docker build -t db .
 - cd ../app
 - docker build -t app .
 - docker run --name db_service -e MYSQL_ROOT_PASSWORD=root -d db
 - docker ps
 - docker run --name app_service --link db_service -d app python app.py
 only :
  changes:
  - Dockerfile
  - app/Dockerfile
  - docker-compose
  - app/requirements.txt
  
test:
 script:
 - echo "sono nella fase di test"
 - cd db
 - docker build -t db .
 - cd ../app
 - docker build -t app .
 - docker image ls
 - docker run --name db_service -e MYSQL_ROOT_PASSWORD=root -d db
 - docker run --name app_service --link db_service -d app  
 - docker ps 
 - docker container start app_service
 - docker exec app_service python test.py
