image: python:2.7


before_script:
- pip install -r requirements.txt
    
stages:
- build
- test
- deploy

pages:
 stage: build
 image: docker:17.06.0-ce
 services:
  - docker:17.06.0-ce-dind
 script:
  # Install Docker Compose
  - pip install docker-compose
  - docker-compose --build

build:
 script:
 - echo "sono nella fase di build"
 #- docker-compose up    
 #only :
  #changes:
  #- Dockerfile
  #- app/Dockerfile
  #- docker-compose
  #- requirements

test:
 script:
 - echo "sono nella fase di test"
 #- python -m pytest tests/test.py
 - python tests/test.py
     
deploy:
 script:
 - echo "sono nella fase di deploy"
     
     
