image: docker:stable

services:
  - docker:18.06-dind
  
before_script:
- apk add --update python py-pip python-dev 
- pip install docker-compose 
- pip install --upgrade pip
- docker-compose build 
- docker-compose run web

stages:
- build
- test

build:
 stage: build
 script:
   - echo "Build successfull"

test:
 stage: test
 script:
 - echo "Start testing"
 - docker ps
 - docker-compose exec -T web python -m pytest -q /code/tests/test_templates.py 
 - echo "End testing"