version: '2'
services:

  web:
    build: app/.
    ports:
      - "8082:8082"
    volumes:
     - .:/code
    links:
      - db
    depends_on:
      - db

  db:
    build: db/.
    hostname: mysqlserver
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: 1
       MYSQL_PASSWORD: 1
       MYSQL_DATABASE: AppDB
