version: '2'
services:

  web:
    build: web/.
    ports:
      - "8082:8082"
    volumes:
      - .:/code
    links:
      - database

  database:
    build: db/.
    ports:
      - "32000:3306"
    hostname: mysqlserver
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 1
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: AppDB
      MYSQL_HOSTNAME: database

